DROP DATABASE IF EXISTS goj;

CREATE DATABASE goj;

use goj;

CREATE TABLE `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(40) NOT NULL COMMENT '用户名',
  `email` VARCHAR(254) COMMENT '邮箱',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  CONSTRAINT `username` UNIQUE (username),
  CONSTRAINT `email` UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

CREATE TABLE `user_auth` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `type` VARCHAR(10) NOT NULL COMMENT '验证类型',
  `identifier` VARCHAR(255) NOT NULL COMMENT '唯一标识',
  `credential` VARCHAR(255) NOT NULL COMMENT '密码凭证',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id),
  CONSTRAINT `identifier` UNIQUE (identifier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user_profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `avatar` VARCHAR(2083) COMMENT '头像链接',
  `description` TEXT COMMENT '个人简介',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `role` ENUM('用户', '管理员') NOT NULL COMMENT '用户角色' DEFAULT '用户',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `problems` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '题目ID',
  `name` VARCHAR(20) NOT NULL COMMENT '题目名称',
  `difficulty` ENUM('简单', '中等', '困难') NOT NULL COMMENT '难度',
  `description` TEXT NOT NULL COMMENT '题目描述',
  `tlimit` INT UNSIGNED NOT NULL COMMENT '时间限制-ms',
  `rlimit` INT UNSIGNED NOT NULL COMMENT '内存限制-ms',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `submissions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '提交ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `problem_id` INT UNSIGNED NOT NULL COMMENT '题目ID',
  `language` TINYINT(3) UNSIGNED NOT NULL COMMENT '编程语言',
  `result` TINYINT(1) UNSIGNED NOT NULL COMMENT '运行结果',
  `code` TEXT NOT NULL COMMENT '代码',
  `tusage` INT UNSIGNED NOT NULL COMMENT '时间消耗-ms',
  `rusage` INT UNSIGNED NOT NULL COMMENT '内存消耗-ms',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (problem_id) REFERENCES problems (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `testcase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '测试用例ID',
  `problem_id` INT UNSIGNED NOT NULL COMMENT '题目ID',
  `input` TEXT NOT NULL COMMENT '输入',
  `output` TEXT NOT NULL COMMENT '输出',
  PRIMARY KEY (id),
  FOREIGN KEY (problem_id) REFERENCES problems (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
